### PR TITLE
Hide MPV player if there is no video stream

### PR DESCRIPTION
**Pull request by core1024**
If you played a movie and then play audio only stream the last image of the player was shown in the background.

Before:
image

After:
image

### CODE REVIEW

**Review by jaruba — APPROVED** [review]

**Comment by jaruba** [comment]
I know the issue, and the code looks ok, @core1024 if you feel confident in your changes you can merge.

**Comment by Ivshti** [comment]
@core1024 @jaruba I don't see the value in this PR.

In fact, I think it can have negative value.

if for example I'm playing music, and the file has an album cover image, mpv will display this, making it way better than just a blank screen

for me it doesn't make any sense to hide any visual info that mpv would decide to display

**Comment by jaruba** [comment]
@Ivshti Before this change, when an audio file would be played and it had no image, it would show the last video frame of the last video played. So I would listen to a podcast and i would have PewDiePie's face in Stremio from the last YT video played.

**Comment by Ivshti** [comment]
after this change, would we still show images if the audio file has one?

**Comment by jaruba** [comment]
I believe so, it should only clear the video frames after playback has stopped, we will test for this case too. But I don't think it should break that case.

**Comment by jaruba** [comment]
Actually looking at the code again, it might indeed break it, i guess tests will tell, but it might indeed not be the correct solution for that issue.

**Comment by jaruba** [comment]
@Ivshti Although i was 100% sure you were right after re-checking the code, it turns out.. you were not...

I just tested this branch with "Today's Top Tune" from the Podcasts addon (you can search for "podcast:today's top tune" to find the channel). I checked the Network tab in Chrome and it provides `mp3` streams that have artwork. The artwork is shown for the build of this branch also, while it does indeed remove the wrong frame from other audio streams that lack artwork.

So it seems to fix the issue without sacrificing artwork from metadata.

**Review by Ivshti — APPROVED** [review]

**Pull request merged**
