### PR TITLE
Cmake build system and update of singleapplication module to v3.2.0 and Qt to 5.15.2

### PR DESCRIPTION
**Pull request by core1024**
This is needed in order the flatpak package to find qt5webengine as it is not in standard location and `qmake` is not flexible enough.

When using CMake `autoupdater.h` got included twice for some reason and I added `#include guards` in order to avoid this.

The current version of singleapplication does not support CMake so I've updated it.

The `FindMPV.cmake` script is borrowed from Plex media player project.

All platforms use this system.

### CODE REVIEW

**Review by TRtomasz — COMMENTED** [review]
I see that build has failed due to network issue, can you rerun the checks?
Also i see that we updated VS version, is there some issue with VS? If no perhaps it is better to update to 2019 instead 2017

**Comment by core1024** [comment]
> I see that build has failed due to network issue, can you rerun the checks?
> Also i see that we updated VS version, is there some issue with VS? If no perhaps it is better to update to 2019 instead 2017

I have more changes to come. I'll take a look at the Visual Studio case. Maybe I'll update the Qt5 version too as I am not sure if the current version supports VS2019. Also there are some issues with MacOS due to changes in inna. I'll fix that in another PR.

**Comment by jaruba** [comment]
me scrolling through this PR: _the great wall of vladi_

**Review by shteryana — APPROVED** [review]
Tested the MAC OS CI build artifacts & verified working properly on Mac OS Catalina 10.15.7 & Mac OS Big Sur 11.2.1

**Pull request merged**
