### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by OmarMesqq**
Hi! I made some changes to Stremio's documentation.

### Files changed: 

`DEBIAN.md`

- Fixed some typos, markdown bad formatting 
- Removed all the sections related to dependencies and made all of them available in a single section (3.1) 

`README.md`

- Grammar and typos 

Please, let me know if there are any disagreements in the changes.

### CODE REVIEW

**Comment by Ivshti** [comment]
why are the "if you get X message" pieces removed? They seem like valuable info

**Comment by OmarMesqq** [comment]
@Ivshti On Ubuntu 20.04 and 22.04, installing the necessary dependencies I listed shouldn't throw any "missing library" errors like these.

I just reduced the install instructions for simplicity. Again, I don't know if everyone agrees on this point. 

By the way, do you have any info on the CI processes? My build won't pass on Mac OS. I even removed some changes I proposed to the Docker build process from this PR.

**Comment by TRtomasz** [comment]
@OmarMesqq it is not caused by your changes. It is moste likely caused by changes made to IIna player, i see they migrated  to mpv 0.35.1 an ffmepg 6.0 right after last successfull CI build

**Comment by OmarMesqq** [comment]
Thanks for the info, @TRtomasz ! Do you know when CI will be back to normal? In the meantime, I will work on the Docker changes locally. 

And, of course, when CI is normal again and you guys agree on my doc changes, this PR should be merged to declutter the repo :)

Also, @Ivshti , do you agree with my changes or should I edit it?

**Pull request closed without merging**
